CREATE TABLE modelrec(
  name           VARCHAR(97) NOT NULL PRIMARY KEY
  ,city           VARCHAR(25) NOT NULL
  ,student_fees   NUMERIC(19,10) NOT NULL
  ,highest_degree INTEGER  NOT NULL
  ,staff_fte      NUMERIC(9,4) NOT NULL
  ,web_pages      VARCHAR(37)
);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Vienna','Vienna',17131218.28,3,6378.5469,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Graz','Graz',3628120.01,3,2738.7869,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Innsbruck','Innsbruck',3890197.44,3,3122.686,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Salzburg','Salzburg',2669432.9,3,1730.8032,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Vienna University of Technology','Vienna',7284097.67,3,3929.7488,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Graz University of Technology','Graz',3193395.39,3,2637.8773,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Leoben','Leoben',797398.87,3,932.2882,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Veterinary Medicine Vienna','Vienna',214874.11,3,1155.4197,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Vienna University of Economics and Business','Vienna',3392025.05,3,1515.9303,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Linz','Linz',4090152.98,3,2130.8351,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Klagenfurt','Klagenfurt',1384511.44,3,884.1888,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University for Continuing Education Krems','Krems an der Donau',20135148.24,3,608.898,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Medical University of Vienna','Vienna',1022496.65,3,4841.86,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Medical University of Graz','Graz',440571.78,3,2074.5977,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Medical University of Innsbruck','Innsbruck',436366.56,3,1720.2657,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Academy of Fine Arts Vienna','Vienna',460341.62,3,344.3375,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Arts Vienna','Vienna',362953.53,3,523.7976,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music and Performing Arts in Vienna','Vienna',745822.89,3,989.8833,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University Mozarteum Salzburg','Salzburg',425187.94,3,518.7885,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music and Performing Arts Graz','Graz',390183.86,3,509.4106,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Art and Design Linz','Linz',371372.27,3,266.6445,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('KU Leuven','Leuven',63873623.3,3,12350.11,'[''https://www.kuleuven.be/kuleuven/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hasselt University','Diepenbeek',5495348.44,3,1494.45,'[''http://www.uhasselt.be/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Antwerp','Antwerp',24504447.0,3,4018.7,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ghent University','Gent',45547751.0,3,8937.74,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('The Vrije Universiteit Brussel','Ixelles',18861306.88,3,3617.53,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Cyprus','Nicosia',20256228.0,3,1231.0,'[''http://www.ucy.ac.cy/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Open University of Cyprus','Latsia',3645569.0,3,89.0,'[''http://www.ouc.ac.cy/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Cyprus University of Technology','Limassol',8545604.0,3,569.0,'[''http://www.cut.ac.cy/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Freiburg','Freiburg im Breisgau',3805051.0,3,4080.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Heidelberg University','Heidelberg',4980816.0,3,4417.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Hohenheim','Stuttgart',2523644.0,3,1737.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Karlsruhe Institute of Technology','Karlsruhe',3988020.0,3,4854.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Konstanz','Konstanz',2540529.0,3,2157.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Mannheim','Mannheim',3066713.0,3,1445.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Stuttgart','Stuttgart',9951796.0,3,5366.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('TÃ¼bingen University','TÃ¼bingen',9960685.0,3,4100.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ulm University','Ulm',2984095.0,3,1599.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Zeppelin University Friedrichshafen (Priv. H)','Friedrichshafen',4840521.0,3,198.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule fÃ¼r jÃ¼dische Studien Heidelberg','Heidelberg',1070.0,3,38.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Augsburg','Augsburg',263996.0,3,2041.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Bamberg','Bamberg',801873.0,3,1213.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Bayreuth','Bayreuth',337173.0,3,2274.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Catholic University of EichstÃ¤tt-Ingolstadt','EichstÃ¤tt',338441.0,3,723.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Erlangen-NÃ¼rnberg','Erlangen',58401.0,3,5400.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ludwig Maximilian University of Munich','Munich',472208.0,3,6529.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technical University of Munich','Munich',6628107.0,3,8786.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Bundeswehr University Munich','Neubiberg',3034683.0,3,1688.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Passau','Passau',21347.0,3,1116.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Regensburg','Regensburg',0.0,3,2877.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of WÃ¼rzburg','WÃ¼rzburg',1132628.0,3,3923.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Free University of Berlin','Berlin',5569160.0,3,4994.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technical University of Berlin','Berlin',8932134.0,3,4887.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Humboldt University of Berlin','Berlin',3849191.0,3,4123.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('ESCP-EAP European School of Management','Berlin',6801443.0,3,122.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hertie School of Governance','Berlin',7322905.0,3,232.0,'[''http://www.hertie-school.org/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Steinbeis University','Magdeburg',20322719.0,3,238.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Viadrina European University','Frankfurt (Oder)',1045437.0,3,516.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Potsdam','Potsdam',2222720.0,3,2694.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Bremen','Bremen',2869911.0,3,3004.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Constructor University Bremen gGmbH (Priv. U)','Bremen',30568016.0,3,396.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Hamburg','Hamburg',6279222.0,3,5364.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hamburg University of Technology','Hamburg',824091.0,3,1615.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('HafenCity University Hamburg','Hamburg',268193.0,3,318.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Helmut Schmidt University of the Federal Armed Forces Hamburg','Hamburg',417786.0,3,1140.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Bucerius Law School','Hamburg',6718661.0,3,139.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technical University of Darmstadt','Darmstadt',2811385.0,3,4498.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Frankfurt University','Frankfurt am Main',5640624.0,3,4155.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Justus Liebig University Giessen','GieÃŸen',3167041.0,3,3909.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Kassel','Kassel',2469693.0,3,2784.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Philipps University of Marburg','Marburg',5179763.0,3,3224.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Frankfurt School of Finance & Management-HfB (Priv. H)','Frankfurt am Main',56731563.0,3,257.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('EBS University of Business and Law','Oestrich-Winkel',18988418.0,3,207.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Greifswald','Greifswald',560100.0,3,1204.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Rostock','Rostock',299686.0,3,1850.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Brunswick University of Technology','Braunschweig',749527.0,3,3334.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Clausthal University of Technology','Clausthal',140390.0,3,1010.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Georg August GÃ¶ttingen University','GÃ¶ttingen',4339665.0,3,4107.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Hannover','Hannover',1971049.0,3,4191.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Veterinary Medicine Hannover','Hannover',349344.0,3,1085.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Hildesheim','Hildesheim',1568815.0,3,839.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Leuphana University of LÃ¼neburg','LÃ¼neburg',1542497.0,3,1049.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Carl von Ossietzky the University of Oldenburg','Oldenburg',752421.0,3,2413.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('OsnabrÃ¼ck University','OsnabrÃ¼ck',477963.0,3,1541.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Vechta','Vechta',137410.0,3,456.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Aachen University','Aachen',1955171.0,3,8404.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Bielefeld University','Bielefeld',1101094.0,3,3379.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ruhr-University Bochum','Bochum',424709.0,3,5362.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Bonn','Bonn',0.0,3,4581.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('TU Dortmund University','Dortmund',123353.0,3,3816.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Heinrich Heine University DÃ¼sseldorf','DÃ¼sseldorf',0.0,3,2378.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Duisburg-Essen','Essen',844613.0,3,4053.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Hagen','Hagen',16874556.0,3,1321.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Cologne','Cologne',747348.0,3,4894.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('German Sport University Cologne','Cologne',221159.0,3,584.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of MÃ¼nster','MÃ¼nster',2862051.0,3,4825.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Paderborn','Paderborn',81967.0,3,2475.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Siegen','Siegen',202107.0,3,1977.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Wuppertal','Wuppertal',119172.0,3,2310.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University Witten/Herdecke','Witten-Herdecke',6785989.0,3,659.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Kaiserslautern','Kaiserslautern',4444992.0,3,2943.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Koblenz','Koblenz',3401105.0,3,649.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Johannes Gutenberg University Mainz','Mainz',1242500.0,3,3887.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('German University of Administrative Sciences Speyer','Speyer',53790.0,3,120.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Trier','Trier',926741.0,3,1202.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('WHU â€“ Otto Beisheim School of Management','Vallendar',24867293.0,3,372.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Saarland University','SaarbrÃ¼cken',2995729.0,3,2274.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Chemnitz University of Technology','Chemnitz',392629.0,3,2091.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technische UniversitÃ¤t Dresden','Dresden',1579320.0,3,6286.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technische UniversitÃ¤t Bergakademie Freiberg','Freiberg',322340.0,3,1405.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Leipzig University','Leipzig',484442.0,3,3704.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('HHL Leipzig Graduate School of Management','Leipzig',5676156.0,3,111.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Martin Luther University','Halle (Saale)',635741.0,3,2517.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Otto von Guericke University of Magdeburg','Magdeburg',199688.0,3,1719.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Flensburg','Flensburg',200960.0,3,587.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Kiel','Kiel',481343.0,3,3474.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of LÃ¼beck','LÃ¼beck',207445.0,3,716.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Erfurt','Erfurt',234913.0,3,747.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ilmenau University of Technology','Ilmenau',541046.0,3,1301.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Friedrich-Schiller-University of Jena','Jena',833820.0,3,3329.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Bauhaus-UniversitÃ¤t Weimar','Weimar',347763.0,3,876.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Education Freiburg','Freiburg im Breisgau',923250.0,3,433.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Education Heidelberg','Heidelberg',726420.0,3,397.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Education Karlsruhe','Karlsruhe',719207.0,3,330.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Education Ludwigsburg','Ludwigsburg',1000844.0,3,410.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Education SchwÃ¤bisch GmÃ¼nd','SchwÃ¤bisch GmÃ¼nd',533167.0,3,268.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Education Weingarten','Weingarten',563020.0,3,269.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Munich School of Philosophy','Munich',205978.0,3,38.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Augustana-Hochschule Neuendettelsau (ev)','Neuendettelsau',4550.0,3,42.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Philosophisch-Theologische Hochschule Frankfurt a.M. (rk)','Frankfurt am Main',102119.0,3,41.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fulda Faculty of Theology','Fulda',281.0,3,22.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Faculty of Theology in Paderborn','Paderborn',0.0,3,35.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Cologne University of Catholic Theology','Cologne',34793.0,3,19.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Kirchliche Hochschule Wuppertal / Bethel (ev)','Wuppertal',0.0,3,29.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Faculty of Theology Trier','Trier',100.0,3,26.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music Freiburg','Freiburg im Breisgau',129496.0,3,166.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('State Academy of Fine Arts Karlsruhe','Karlsruhe',138083.0,3,61.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Karlsruhe College of Arts and Design','Karlsruhe',264775.0,3,56.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music Karlsruhe','Karlsruhe',485831.0,3,142.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Mannheim University of Music and Performing Arts','Mannheim',236805.0,3,133.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Stuttgart State Academy of Art and Design','Stuttgart',0.0,3,162.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('State University of Music and the Performing Arts Stuttgart','Stuttgart',710006.0,3,232.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Trossingen School of Music','Trossingen',188916.0,3,101.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music and Performing Arts Munich','Munich',262483.0,3,292.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music WÃ¼rzburg','WÃ¼rzburg',109599.0,3,149.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Berlin University of the Arts','Berlin',729828.0,3,909.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Film University Babelsberg Konrad Wolf','Potsdam',127892.0,3,247.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Fine Arts of Hamburg','Hamburg',84548.0,3,103.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hamburg University of Music and Theater','Hamburg',681521.0,3,262.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Frankfurt University of Music and Performing Arts','Frankfurt am Main',187727.0,3,227.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Offenbach Academy of Art and Design','Offenbach am Main',89539.0,3,129.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Braunschweig University of Art','Braunschweig',65917.0,3,160.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Detmold Music School','Detmold',96300.0,3,185.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Kunstakademie DÃ¼sseldorf','DÃ¼sseldorf',0.0,3,110.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Robert Schumann School of Music and Media','DÃ¼sseldorf',0.0,3,163.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Folkwang University of the Arts','Essen',1088691.0,3,333.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Academy of Media Arts','Cologne',0.0,3,125.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Cologne University of Music and Dance','Cologne',177828.0,3,299.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Academy of Fine Arts MÃ¼nster','MÃ¼nster',3982.0,3,67.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Dresden Academy of Fine Arts','Dresden',68064.0,3,122.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music Carl Maria von Weber Dresden','Dresden',446097.0,3,175.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music & Theatre Leipzig','Leipzig',43120.0,3,248.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Burg Giebichenstein University of Art and Design Halle','Halle (Saale)',132903.0,3,235.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Muthesius Academy of Fine Arts and Design','Kiel',1940.0,3,100.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music LÃ¼beck','LÃ¼beck',207700.0,3,115.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Music Franz Liszt Weimar','Weimar',161832.0,3,271.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Brandenburg University of Applied Sciences','Brandenburg',437445.0,3,261.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hamburg University of Applied Sciences','Hamburg',1873134.0,3,1437.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fulda University of Applied Sciences','Fulda',1952166.0,3,788.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('RheinMain University of Applied Sciences','Wiesbaden',1721365.0,3,1006.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Aachen University of Applied Sciences','Aachen',1957733.0,3,1000.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Bielefeld University of Applied Sciences','Bielefeld',963663.0,3,869.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Bochum University of Applied Sciences','Bochum',130585.0,3,563.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Bonn-Rhein-Sieg','Sankt Augustin',179290.0,3,739.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Dortmund University of Applied Sciences and Arts','Dortmund',14400.0,3,893.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('DÃ¼sseldorf University of Applied Sciences','DÃ¼sseldorf',0.0,3,790.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('WestfÃ¤lische Hochschule Gelsenkirchen Bocholt Recklinghausen','Gelsenkirchen',0.0,3,686.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Cologne University of Applied Sciences','Cologne',589827.0,3,1819.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ostwestfalen-Lippe University of Applied Sciences','Lemgo',6045.0,3,704.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Niederrhein University of Applied Sciences','MÃ¶nchengladbach',485662.0,3,1022.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('South Westphalia University of Applied Sciences','Hagen',16714.0,3,874.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Georg Agricola University of Applied Sciences','Bochum',0.0,3,221.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Rheinland-Westfalen-Lippe Protestant University of Applied Sciences','Bochum',26059.0,3,175.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Dresden University of Applied Sciences','Dresden',82621.0,3,615.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Zittau/GÃ¶rlitz University of Applied Sciences','Zittau',111314.0,3,449.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Anhalt University of Applied Sciences','KÃ¶then',4161649.0,3,689.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Harz University of Applied Sciences','Wernigerode',345673.0,3,268.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Magdeburg-Stendal University of Applied Sciences','Magdeburg',731073.0,3,561.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Merseburg University of Applied Sciences','Merseburg',20115.0,3,343.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Jena','Jena',321666.0,3,481.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('KÃ¼hne Logistics University','Hamburg',3207703.0,3,177.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Rhine-Waal University of Applied Sciences','Kleve',97140.0,3,526.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ruhr West University of Applied Sciences','MÃ¼lheim an der Ruhr',0.0,3,521.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Brandenburg University of Technology (BTU) Cottbus â€“ Senftenberg','Cottbus',740545.0,3,1682.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule Geisenheim University (FH)','Geisenheim',210243.0,3,481.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Brandenburg Medical School Theodor Fontane','Brandenburg',1751760.0,3,99.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Copenhagen','Copenhagen',14134664.402958032,3,10387.88,'[''http://www.ku.dk/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Aarhus University','Aarhus',9261382.383336242,3,8490.47,'[''http://www.au.dk/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Southern Denmark','Odense',13114388.865774604,3,4068.5,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Roskilde University','Roskilde',3735119.247339248,3,940.6,'[''http://www.ruc.dk/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Aalborg University','Aalborg',10722086.32514193,3,3451.37,'[''http://www.auc.dk/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technical University of Denmark','Lyngby',12757505.267819997,3,6085.0,'[''http://www.dtu.dk/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Copenhagen Business School','Frederiksberg',22677378.57171617,3,1642.15,'[''http://www.cbs.dk/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('IT University of Copenhagen','Copenhagen',1016387.2820733066,3,457.01,'[''http://www.itu.dk/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Tartu','Tartu',10118413.87,3,3540.0,'[''http://www.ut.ee/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Tallinn University of Technology','Tallinn',5633719.030000001,3,1720.0,'[''http://www.ttu.ee/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Tallinn University','Tallinn',5413597.199999999,3,845.0,'[''http://www.tlu.ee/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Estonian University of Life Sciences','Tartu',2316152.05,3,835.0,'[''http://www.emu.ee/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Estonian Academy of Arts','Tallinn',1077167.59,3,230.0,'[''http://www.artun.ee/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Estonian Academy of Music and Theatre','Tallinn',467332.9,3,220.0,'[''http://www.ema.edu.ee/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Erasmus University College Brussels','Anderlecht',4519376.88,2,572.16,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Antwerp maritime academy','Antwerp',485595.67,2,47.15,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University College Ghent','Gent',13124494.48,2,1158.66,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('LUCA School of Arts','Schaarbeek',2754763.6099999985,2,450.85,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Karel de Grote University College','Antwerp',10056384.959999518,2,839.73,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('AP University College Antwerpen','Antwerp',9837697.019999914,2,1046.5,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('PXL University College','Hasselt',7066920.779999999,2,678.65,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University college Arteveldehogeschool','Gent',12023040.44,1,915.02,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Thomas More Kempen','Geel',6612935.449999999,1,575.48,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('UC Leuven','Leuven',8687235.360000001,1,601.14,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('UC Limburg','Diepenbeek',4580458.47,1,358.96,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Catholic University College Vives Zuid','Kortrijk',10113420.64,1,715.2,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('ODISEE','Brussels',11124210.19,1,759.61,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Thomas More Mechelen-Antwerpen','Mechelen',9028823.0,1,580.38,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Allensbach University','Konstanz',2035771.0,2,21.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Bavarian School of Public Policy','Munich',0.0,2,44.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Dresden International University GmbH','Dresden',4086545.0,2,40.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Friedensau Adventist University','MÃ¶ckern',716289.0,2,58.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Academy of Fine Arts in Munich','Munich',3797.0,2,126.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Television and Film Munich','Munich',34451.0,2,104.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Academy of Fine Arts in Nuremberg','Nuremberg',1605.0,2,58.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Nuremberg School of Music','Nuremberg',47448.0,2,119.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('WeiÃŸensee Academy of Art Berlin','Berlin',143439.0,2,145.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Academy of Music Hanns Eisler Berlin','Berlin',246700.0,2,180.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ernst Busch Academy of Dramatic Art','Berlin',51271.0,2,111.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of the Arts Bremen','Bremen',166331.0,2,174.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Alfter',6655660.0,2,156.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule der Bildenden KÃ¼nste SaarbrÃ¼cken','SaarbrÃ¼cken',73392.0,2,62.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Palucca University of Dance Dresden','Dresden',119268.0,2,67.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Academy of Visual Arts Leipzig','Leipzig',57506.0,2,100.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Aalen University','Aalen',1292976.0,2,640.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Albstadt-Sigmaringen University','Albstadt',1257048.0,2,289.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Biberach University of Applied Sciences','Biberach an der Riss',691822.0,2,298.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Esslingen','Esslingen am Neckar',1252878.0,2,669.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Furtwangen University','Furtwangen im Schwarzwald',2008247.0,2,684.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Heilbronn University of Applied Sciences','Heilbronn',1499649.0,2,729.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Karlsruhe University of Applied Sciences','Karlsruhe',1636954.0,2,715.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Labour Studies of the Federal Employment Agency','Mannheim',0.0,2,166.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Mannheim','Mannheim',1024450.0,2,538.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Nuertingen-Geislingen University','Geislingen an der Steige',925093.0,2,469.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Offenburg University','Offenburg',1169977.0,2,476.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Ravensburg-Weingarten','Weingarten',910523.0,2,311.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Reutlingen University','Reutlingen',1465505.0,2,638.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Forest Sciences Rottenburg','Rottenburg am Neckar',203080.0,2,96.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Design SchwÃ¤bisch-GmÃ¼nd','SchwÃ¤bisch GmÃ¼nd',133429.0,2,86.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Stuttgart University of Applied Sciences','Stuttgart',990370.0,2,423.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Ulm','Ulm',396270.0,2,338.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Heidelberg',24290254.0,2,274.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('SRH Fernhochschule Riedlingen','Riedlingen',27609460.0,2,251.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Freiburg im Breisgau',727427.0,2,69.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Evangelische Hochschule Ludwigsburg','Ludwigsburg',270657.0,2,75.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Catholic University of Applied Sciences Freiburg','Freiburg im Breisgau',1260656.0,2,139.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ostbayerische Technische Hochschule Amberg-Weiden','Amberg',586073.0,2,413.0,'[''https://www.oth-aw.de/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ansbach University of Applied Sciences','Ansbach',364520.0,2,335.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Aschaffenburg University of Applied Sciences','Aschaffenburg',426396.0,2,365.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Augsburg University of Applied Sciences','Augsburg',508107.0,2,634.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Coburg University of Applied Sciences','Coburg',1116128.0,2,494.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Deggendorf Institute of Technology','Deggendorf',2199416.0,2,1071.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hof University of Applied Sciences','Hof',3690949.0,2,428.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technische Hochschule Ingolstadt','Ingolstadt',1614229.0,2,782.0,'[''https://www.thi.de/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Kempten University of Applied Sciences','Kempten',1057272.0,2,577.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Landshut','Landshut',100.0,2,393.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Munich University of Applied Sciences','Munich',162703.0,2,1454.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Neu-Ulm University of Applied Sciences','Neu-Ulm',12835.0,2,294.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technische Hochschule NÃ¼rnberg Georg Simon Ohm','Nuremberg',1245807.0,2,1243.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ostbayerische Technische Hochschule Regensburg','Regensburg',1141093.0,2,928.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Rosenheim University of Applied Sciences','Rosenheim',1186278.0,2,610.0,'[''https://th-rosenheim.de/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Weihenstephan-Triesdorf University of Applied Sciences','Freising',358456.0,2,745.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences WÃ¼rzburg-Schweinfurt','Schweinfurt',101008.0,2,803.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Management','Erding',14705289.0,2,127.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Macromedia University of Applied Sciences','Munich',46147278.0,2,437.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Munich Business School MÃ¼nchen (Priv. FH)','Munich',6711203.0,2,53.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Evangelische Hochschule NÃ¼rnberg (FH)','Nuremberg',330319.0,2,122.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Katholische Stiftungsfachhochschule MÃ¼nchen','Munich',544552.0,2,226.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Alice Salomon Hochschule Berlin','Berlin',437318.0,2,342.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Beuth University of Applied Sciences','Berlin',1313519.0,2,879.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Berlin University of Applied Sciences','Berlin',4698778.0,2,1041.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Berlin School of Economics and Law','Berlin',3942677.0,2,777.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('bbw University of Applied Sciences','Berlin',5124591.0,2,63.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule fÃ¼r Gesundheit und Sport Berlin (Priv. FH)','Berlin',8301249.0,2,82.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('IB-Hochschule Berlin (Priv. FH)','Berlin',3555074.0,2,65.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Mediadesign University of Applied Sciences','Berlin',7952140.0,2,77.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('SRH University Berlin','Berlin',23834936.0,2,249.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Protestant Fachhochschule Berlin','Berlin',156630.0,2,139.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Catholic University for Applied Sciences Berlin','Berlin',647887.0,2,116.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences in Eberswalde','Eberswalde',228669.0,2,378.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Potsdam University of Applied Sciences','Potsdam',544881.0,2,362.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technical University of Applied Sciences Wildau','Wildau',1677444.0,2,403.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('City University of Applied Sciences Bremen','Bremen',828554.0,2,674.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Bremerhaven','Bremerhaven',272884.0,2,284.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Apollon','Bremen',10328219.0,2,119.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('EuropÃ¤ische FernHochschule Hamburg GmbH Hamburg (Priv. FH)','Hamburg',26729200.0,2,228.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('HFH Hamburger Fern-Hochschule (Priv. FH)','Hamburg',31633088.0,2,548.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('HSBA Hamburg School of Business Administration (Priv. FH)','Hamburg',6725670.0,2,64.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Darmstadt University of Applied Sciences','Darmstadt',1690257.0,2,1253.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Frankfurt University of Applied Sciences','Frankfurt am Main',1827433.0,2,1075.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technische Hochschule Mittelhessen','GieÃŸen',1605497.0,2,1119.0,'[''https://www.thm.de/'']');
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('accadis Hochschule Bad Homburg (Priv. FH)','Bad Homburg',4062433.0,2,35.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Wilhelm BÃ¼chner Hochschule Darmstadt (Priv. Fern-FH)','Pfungstadt',16224959.0,2,153.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fresenius University Applied Sciences','Idstein',89001119.0,2,1048.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('DIPLOMA Hochschule','BÃ¼ckeburg',16502321.0,2,201.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Neubrandenburg University of Applied Sciences','Neubrandenburg',224768.0,2,282.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Stralsund University of Applied Sciences','Stralsund',5122.0,2,253.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Ostfalia University of Applied Sciences','WolfenbÃ¼ttel',1304855.0,2,896.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hannover University of Applied Sciences and Arts','Hannover',248000.0,2,864.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences and Arts Hildesheim/Holzminden/GÃ¶ttingen','Hildesheim',539267.0,2,773.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('OsnabrÃ¼ck University of Applied Sciences','OsnabrÃ¼ck',2679136.0,2,1360.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('PFH â€“ Private University of Applied Sciences','GÃ¶ttingen',16004702.0,2,116.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences in Hannover','Hannover',3813119.0,2,22.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('HKS - University of applied sciences and arts in Ottersberg','Ottersberg',1308770.0,2,34.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Private Hochschule fÃ¼r Wirtschaft und Technik Vechta/Diepholz/Oldenburg','Vechta',2377357.0,2,66.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('MÃ¼nster University of Applied Sciences','MÃ¼nster',0.0,2,1245.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('IU International University of Applied Sciences','Bad Honnef',443425244.0,2,1291.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Bielefeld',27663758.0,2,216.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('EBZ Business School - University of Applied Sciences','Bochum',3900068.0,2,56.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences - Bonn','Bonn',2874509.0,2,75.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('European University of Applied Sciences','BrÃ¼hl',14526319.0,2,132.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('FOM University of Applied Sciences','Essen',161823693.0,2,1390.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('SRH Hochschule fÃ¼r Logistik und Wirtschaft Hamm (Priv. FH)','Hamm',5536212.0,2,71.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Europe for Applied Sciences','Iserlohn',36537265.0,2,180.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Rheinische Fachhochschule Cologne','Cologne',0.0,2,275.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Private Fachhochschule der Wirtschaft Paderborn','Paderborn',13715199.0,2,86.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fachhochschule der Diakonie Bielefeld-Bethel','Bielefeld',2441114.0,2,30.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Nordrhein-Westfalen Catholic University of Applied Sciences','MÃ¼nster',989788.0,2,477.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('TH Bingen University of Applied Sciences','Bingen am Rhein',571224.0,2,232.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Kaiserslautern University of Applied Sciences','Kaiserslautern',8422.0,2,506.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Koblenz University of Applied Sciences','Koblenz',114998.0,2,580.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Ludwigshafen am Rhein','Ludwigshafen am Rhein',85357.0,2,318.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Mainz University of Applied Sciences','Mainz',80709.0,2,514.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Trier University of Applied Sciences','Trier',145687.0,2,676.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Worms University of Applied Sciences','Worms',97239.0,2,240.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Mainz Catholic University of Applied Sciences','Mainz',346092.0,2,109.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences SaarbrÃ¼cken','SaarbrÃ¼cken',1312025.0,2,608.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Mittweida','Mittweida',1591837.0,2,539.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Zwickau','Zwickau',211478.0,2,543.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Flensburg University of Applied Sciences','Flensburg',118553.0,2,298.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Kiel University of Applied Sciences','Kiel',501125.0,2,514.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Technical University LÃ¼beck','LÃ¼beck',713095.0,2,467.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('NORDAKADEMIE University of Applied Sciences','Elmshorn',11403545.0,2,80.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Erfurt University of Applied Sciences','Erfurt',158691.0,2,461.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Nordhausen University of Applied Sciences','Nordhausen',203974.0,2,240.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences Schmalkalden','Schmalkalden',157267.0,2,224.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('SRH University of Applied Sciences Gera','Gera',7421021.0,2,70.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Public Administration Kehl','Kehl',112748.0,2,139.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences - Public Administration and Finance Ludwigsburg','Ludwigsburg',381538.0,2,219.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('FH der Polizei Brandenburg (VerwFH) in Oranienburg','Oranienburg',0.0,2,458.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hessische Hochschule fÃ¼r Polizei und Verwaltung','Wiesbaden',1220956.0,2,312.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Kommunale Hochschule fÃ¼r Verwaltung in Niedersachsen','Hannover',0.0,2,42.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences for Public Administration and Management of North Rhine-Westphalia','Gelsenkirchen',706236.0,2,813.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Federal University of Applied Administrative Sciences','BrÃ¼hl',4.0,2,903.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule fÃ¼r Ã¶ffentliche Verwaltung und Rechtspflege MeiÃŸen (FH)','MeiÃŸen',0.0,2,166.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('ThÃ¼ringer Fachhochschule fÃ¼r Ã¶ffentliche Verwaltung Gotha','Gotha',479965.0,2,87.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('International Psychoanalytic University Berlin','Berlin',6056101.0,2,92.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule Emden/Leer','Emden',88462.0,2,449.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Hamburg',3321876.0,2,26.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hamm-Lippstadt University of Applied Sciences','Hamm',900.0,2,406.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Cologne Business School (CBS) - European University of Applied Sciences (Priv. FH)','Cologne',19373178.0,2,253.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Management Studies','Mannheim',2227859.0,2,55.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Berlin',3545975.0,2,65.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Bard College Berlin','Berlin',8680082.0,2,76.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Bad Liebenzell',1079415.0,2,32.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Akkon University for Applied Sciences','Berlin',5617604.0,2,65.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Potsdam',2557814.0,2,23.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Berlin',10636645.0,2,108.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('YMCA University of Applied Sciences','Kassel',2710532.0,2,31.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Leibniz - Fachhochschule Hannover (Priv. FH)','Hannover',3582198.0,2,29.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fliedner Fachhochschule DÃ¼sseldorf (Priv. )','DÃ¼sseldorf',9696695.0,2,107.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fachhochschule Dresden (Priv. FH)','Dresden',2902265.0,2,44.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Jade University of Applied Sciences','Wilhelmshaven',63000.0,2,640.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'FÃ¼rth',1818067.0,2,25.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'DÃ¼sseldorf',14820749.0,2,78.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Munich',2731576.0,2,28.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Berlin International University of Applied Sciences','Berlin',3421514.0,2,51.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('NBS Northern Business School','Hamburg',2996130.0,2,56.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Cologne',5370538.0,2,75.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Heidelberg',5923119.0,2,38.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Berlin',1439597.0,2,23.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Hamburg',27715.0,2,43.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Idstein',3270932.0,2,34.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Education','Berlin',1359919.0,2,18.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Berlin',1789310.0,2,22.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('CODE University of Applied Sciences','Berlin',2886356.0,2,55.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Essen University of Fine Arts','Essen',2923827.0,2,39.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Hannover',6530392.0,2,38.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Flensburg',0.0,2,32.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Evangelical University of Tabor','Marburg',579856.0,2,18.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Catholic Church Music and Music Education Regensburg','Regensburg',91777.0,2,39.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Catholic University College Vives Noord','Brugge',4046487.86,1,264.14,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('The Cyprus Police Academy','Nicosia',0.0,0,54.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Schwetzingen Technical Institute & Graduate Court Registrars'' College','Schwetzingen',0.0,1,60.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule der Polizei Baden-WÃ¼rttemberg','Villingen-Schwenningen',0.0,1,282.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule fÃ¼r den Ã¶ffentlichen Dienst in Bayern','FÃ¼rstenfeldbruck',0.0,1,481.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fachhochschule fÃ¼r Finanzen Brandenburg in KÃ¶nigs Wusterhausen','KÃ¶nigs Wusterhausen',0.0,1,53.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule fÃ¼r Ã¶ffentliche Verwaltung Bremen','Bremen',57895.0,1,52.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Norddeutsche Akademie fÃ¼r Finanzen und Steuerrecht Hamburg','Hamburg',0.0,1,33.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hessische Hochschule fÃ¼r Finanzen und Rechtspflege','Rotenburg an der Fulda',656550.0,1,107.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fachhochschule fÃ¼r Finanzen NRW','Nordkirchen',1793589.0,1,290.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule fÃ¼r Finanzen Rheinland-Pfalz','Edenkoben',0.0,1,58.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('University of Applied Sciences in Hachenburg','Hachenburg',0.0,1,96.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Hochschule fÃ¼r Ã¶ffentliche Verwaltung Rheinland-Pfalz','Mayen',220652.0,1,87.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fachhochschule fÃ¼r Verwaltung SaarbrÃ¼cken','Quierschied',0.0,1,101.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Fachhochschule fÃ¼r Verwaltung und Dienstleistung Altenholz','Altenholz',9063940.0,1,132.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Freiburg im Breisgau',417909.0,1,4.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Stuttgart',585510.0,1,4.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'BÃ¼chenbeuren',0.0,1,445.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES ('Akademie der Polizei Hamburg','Hamburg',0.0,1,48.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Potsdam',1028192.0,1,15.0,NULL);
INSERT INTO modelrec(name,city,student_fees,highest_degree,staff_fte,web_pages) VALUES (NULL,'Gera',3603.0,1,129.0,NULL);
