-- MOCK DATA

-- Read this script as UTF-8 so any non-ASCII data imports correctly.
SET NAMES utf8mb4;

-- ----Students----------------------------------------------------------------
INSERT INTO student (id, first_name, last_name, email, address, major) VALUES
  (1,  'Maria',    'Lopez',      'marialopez@gmail.com',             '3808 Spaight Way',         'Psychology'),
  (2,  'Corrina',  'Simmens',    'csimmens1@deliciousdays.com',      '53501 Porter Plaza',       'History'),
  (3,  'Bert',     'Hugnin',     'bhugnin2@cbsnews.com',             '75 Clyde Gallagher Pass',  'History'),
  (4,  'Olympia',  'Dewsbury',   'odewsbury3@ucla.edu',              '3456 Green Ridge Park',    'English Literature'),
  (5,  'Ermina',   'Spear',      'espear4@cmu.edu',                  '31 Orin Place',            'Communications'),
  (6,  'Faina',    'Rydzynski',  'frydzynski5@moonfruit.com',        '49 Schiller Court',        'Computer Science'),
  (7,  'Tallia',   'Somerled',   'tsomerled6@goo.ne.jp',             '0773 New Castle Plaza',    'Computer Science'),
  (8,  'Omero',    'Guitonneau', 'oguitonneau7@furl.net',            '07631 Oxford Pass',        'Computer Science'),
  (9,  'Drusilla', 'Boyse',      'dboyse8@mit.edu',                  '95714 Eliot Road',         'Biology'),
  (10, 'Lexi',     'Pellew',     'lpellew9@amazon.co.jp',            '39423 Vahlen Way',         'Engineering'),
  (11, 'Maxim',    'Akett',      'maketta@goo.gl',                   '9433 Lunder Junction',     'Sociology'),
  (12, 'Shane',    'Morsey',     'smorseyb@wix.com',                 '4574 Barnett Crossing',    'Engineering'),
  (13, 'Titus',    'Stillwell',  'tstillwellc@ycombinator.com',      '6137 Lakeland Alley',      'English Literature'),
  (14, 'Chery',    'Lints',      'clintsd@wunderground.com',         '969 Bonner Avenue',        'Engineering'),
  (15, 'Harlie',   'Hellmore',   'hhellmoree@cnn.com',               '59374 Mitchell Terrace',   'English Literature'),
  (16, 'Daniel',   'Wiffield',   'dwiffieldf@chronoengine.com',      '035 Swallow Drive',        'Computer Science'),
  (17, 'Geoffrey', 'Thornton',   'gthorntong@163.com',               '34 Old Gate Street',       'Sociology'),
  (18, 'Betteann', 'Meach',      'bmeachh@xing.com',                 '696 Fair Oaks Point',      'Psychology'),
  (19, 'Corilla',  'Prall',      'cpralli@g.co',                     '022 Badeau Center',        'Business Administration'),
  (20, 'Gary',     'Pechold',    'gpecholdj@slideshare.net',         '22 Warner Hill',           'Business Administration'),
  (21, 'Teddy',    'Ivan',       'tivank@moonfruit.com',             '67 Bellgrove Place',       'Computer Science'),
  (22, 'Cathie',   'Point',      'cpointl@google.es',                '5 Logan Pass',             'Sociology'),
  (23, 'Alys',     'Cantor',     'acantorm@bravesites.com',          '501 Swallow Road',         'Sociology'),
  (24, 'Sampson',  'Bengtsen',   'sbengtsenn@squarespace.com',       '31 Veith Way',             'Biology'),
  (25, 'Ulrica',   'O''Criane',  'uocrianeo@desdev.cn',              '6 Upham Trail',            'Engineering'),
  (26, 'Neel',     'Bray',       'nbrayp@wisc.edu',                  '06 Prairie Rose Trail',    'Biology'),
  (27, 'Shel',     'Braunlein',  'sbraunleinq@discuz.net',           '05 Dapin Circle',          'History'),
  (28, 'Riva',     'Orchart',    'rorchartr@scientificamerican.com', '1 High Crossing Point',    'Business Administration'),
  (29, 'Dayle',    'Ettery',     'detterys@springer.com',            '6693 Corben Road',         'Engineering'),
  (30, 'Auberon',  'Loadman',    'aloadmant@eepurl.com',             '08 Morrow Circle',         'Biology');

-- ----Labor Statisticians-----------------------------------------------------
INSERT INTO labor_statistician (id, first_name, last_name, email) VALUES
  (1,  'Guy',       'Latch',       'glatch0@prnewswire.com'),
  (2,  'Junie',     'Blewitt',     'jblewitt1@narod.ru'),
  (3,  'Freda',     'Schutt',      'fschutt2@dailymotion.com'),
  (4,  'Alphard',   'Heining',     'aheining3@ocn.ne.jp'),
  (5,  'Lucias',    'Dufaur',      'ldufaur4@histats.com'),
  (6,  'Tresa',     'Squelch',     'tsquelch5@seesaa.net'),
  (7,  'Sayre',     'Center',      'scenter6@google.es'),
  (8,  'Meyer',     'Chieco',      'mchieco7@nationalgeographic.com'),
  (9,  'Guthrie',   'Spacy',       'gspacy8@posterous.com'),
  (10, 'Orelia',    'Bottoner',    'obottoner9@youtube.com'),
  (11, 'Cassandre', 'Tacon',       'ctacona@loc.gov'),
  (12, 'Ninon',     'Jowle',       'njowleb@symantec.com'),
  (13, 'Sherrie',   'Lipgens',     'slipgensc@domainmarket.com'),
  (14, 'Olvan',     'Mosby',       'omosbyd@google.nl'),
  (15, 'Pyotr',     'Southam',     'psouthame@soup.io'),
  (16, 'Edik',      'Isles',       'eislesf@washingtonpost.com'),
  (17, 'Billi',     'Yaakov',      'byaakovg@tumblr.com'),
  (18, 'Yorgos',    'Dorbon',      'ydorbonh@mashable.com'),
  (19, 'Elbertine', 'Whines',      'ewhinesi@vistaprint.com'),
  (20, 'Skipper',   'Rickard',     'srickardj@angelfire.com'),
  (21, 'Verney',    'Gownge',      'vgowngek@slate.com'),
  (22, 'Abbey',     'Kingsworth',  'akingsworthl@multiply.com'),
  (23, 'Findley',   'Mews',        'fmewsm@uol.com.br'),
  (24, 'Kathlin',   'Haggett',     'khaggettn@amazon.com'),
  (25, 'Bendick',   'Macias',      'bmaciaso@whitehouse.gov'),
  (26, 'Gilemette', 'Maleck',      'gmaleckp@admin.ch'),
  (27, 'Buddy',     'Fullerlove',  'bfullerloveq@mayoclinic.com'),
  (28, 'Gawen',     'Klimochkin',  'gklimochkinr@themeforest.net'),
  (29, 'Jabez',     'McGray',      'jmcgrays@cornell.edu'),
  (30, 'Rey',       'Satteford',   'rsattefordt@bing.com');

-- ----Budget Managers---------------------------------------------------------
INSERT INTO budget_manager (id, first_name, last_name, email) VALUES
  (1,  'Ashly',     'Josefson',    'ajosefson0@loc.gov'),
  (2,  'Maudie',    'Farney',      'mfarney1@globo.com'),
  (3,  'Lucais',    'Anscombe',    'lanscombe2@utexas.edu'),
  (4,  'Deedee',    'Carnalan',    'dcarnalan3@free.fr'),
  (5,  'Edwina',    'Schwant',     'eschwant4@biblegateway.com'),
  (6,  'Samaria',   'Saintpierre', 'ssaintpierre5@sun.com'),
  (7,  'Beatriz',   'Mattiello',   'bmattiello6@ibm.com'),
  (8,  'Alane',     'MacCostigan', 'amaccostigan7@edublogs.org'),
  (9,  'Raynard',   'Balnave',     'rbalnave8@reddit.com'),
  (10, 'Euell',     'Fugere',      'efugere9@fc2.com'),
  (11, 'Daphna',    'Seydlitz',    'dseydlitza@trellian.com'),
  (12, 'Kennie',    'Szabo',       'kszabob@tripod.com'),
  (13, 'Olia',      'Haryngton',   'oharyngtonc@yellowpages.com'),
  (14, 'Fan',       'Hawket',      'fhawketd@salon.com'),
  (15, 'Skyler',    'Acott',       'sacotte@wordpress.org'),
  (16, 'Sherline',  'Launder',     'slaunderf@marketwatch.com'),
  (17, 'Nolan',     'Munks',       'nmunksg@marketwatch.com'),
  (18, 'Sutton',    'Roust',       'srousth@booking.com'),
  (19, 'Gamaliel',  'Durbann',     'gdurbanni@google.es'),
  (20, 'Rhys',      'Guyonnet',    'rguyonnetj@zdnet.com'),
  (21, 'Barbi',     'Mallinder',   'bmallinderk@wp.com'),
  (22, 'Catharina', 'Jerwood',     'cjerwoodl@cnn.com'),
  (23, 'Clark',     'Frigout',     'cfrigoutm@pcworld.com'),
  (24, 'Letisha',   'Tiffany',     'ltiffanyn@sina.com.cn'),
  (25, 'Jillane',   'Gierek',      'jgiereko@nationalgeographic.com'),
  (26, 'Mac',       'Lean',        'mleanp@sina.com.cn'),
  (27, 'Renae',     'Abramchik',   'rabramchikq@360.cn'),
  (28, 'Cornelius', 'Bierman',     'cbiermanr@com.com'),
  (29, 'Coop',      'Aldiss',      'caldisss@ycombinator.com'),
  (30, 'Connie',    'Hackin',      'chackint@mozilla.com');
