-- MOCK DATA

-- ----Students----------------------------------------------------------------
INSERT INTO student (id, first_name, last_name, email, address, major) VALUES
  (1,  'Tadeo',    'Daskiewicz', 'tdaskiewicz0@spiegel.de',          '3808 Spaight Way',         'Psychology'),
  (2,  'Corrina',  'Simmens',    'csimmens1@deliciousdays.com',      '53501 Porter Plaza',       'History'),
  (3,  'Bert',     'Hugnin',     'bhugnin2@cbsnews.com',             '75 Clyde Gallagher Pass',  'History'),
  (4,  'Olympia',  'Dewsbury',   'odewsbury3@ucla.edu',              '3456 Green Ridge Park',    'English Literature'),
  (5,  'Ermina',   'Spear',      'espear4@cmu.edu',                  '31 Orin Place',            'Communications'),
  (6,  'Faina',    'Rydzynski',  'frydzynski5@moonfruit.com',        '49 Schiller Court',        'Computer Science'),
  (7,  'Tallia',   'Somerled',   'tsomerled6@goo.ne.jp',             '0773 New Castle Plaza',    'Computer Science'),
  (8,  'Omero',    'Guitonneau', 'oguitonneau7@furl.net',            '07631 Oxford Pass',        'Computer Science'),
  (9,  'Drusilla', 'Boyse',      'dboyse8@mit.edu',                  '95714 Eliot Road',         'Biology'),
  (10, 'Lexi',     'Pellew',     'lpellew9@amazon.co.jp',            '39423 Vahlen Way',         'Engineering'),
  (11, 'Maxim',    'Akett',      'maketta@goo.gl',                   '9433 Lunder Junction',     'Sociology'),
  (12, 'Shane',    'Morsey',     'smorseyb@wix.com',                 '4574 Barnett Crossing',    'Engineering'),
  (13, 'Titus',    'Stillwell',  'tstillwellc@ycombinator.com',      '6137 Lakeland Alley',      'English Literature'),
  (14, 'Chery',    'Lints',      'clintsd@wunderground.com',         '969 Bonner Avenue',        'Engineering'),
  (15, 'Harlie',   'Hellmore',   'hhellmoree@cnn.com',               '59374 Mitchell Terrace',   'English Literature'),
  (16, 'Daniel',   'Wiffield',   'dwiffieldf@chronoengine.com',      '035 Swallow Drive',        'Computer Science'),
  (17, 'Geoffrey', 'Thornton',   'gthorntong@163.com',               '34 Old Gate Street',       'Sociology'),
  (18, 'Betteann', 'Meach',      'bmeachh@xing.com',                 '696 Fair Oaks Point',      'Psychology'),
  (19, 'Corilla',  'Prall',      'cpralli@g.co',                     '022 Badeau Center',        'Business Administration'),
  (20, 'Gary',     'Pechold',    'gpecholdj@slideshare.net',         '22 Warner Hill',           'Business Administration'),
  (21, 'Teddy',    'Ivan',       'tivank@moonfruit.com',             '67 Bellgrove Place',       'Computer Science'),
  (22, 'Cathie',   'Point',      'cpointl@google.es',                '5 Logan Pass',             'Sociology'),
  (23, 'Alys',     'Cantor',     'acantorm@bravesites.com',          '501 Swallow Road',         'Sociology'),
  (24, 'Sampson',  'Bengtsen',   'sbengtsenn@squarespace.com',       '31 Veith Way',             'Biology'),
  (25, 'Ulrica',   'O''Criane',  'uocrianeo@desdev.cn',              '6 Upham Trail',            'Engineering'),
  (26, 'Neel',     'Bray',       'nbrayp@wisc.edu',                  '06 Prairie Rose Trail',    'Biology'),
  (27, 'Shel',     'Braunlein',  'sbraunleinq@discuz.net',           '05 Dapin Circle',          'History'),
  (28, 'Riva',     'Orchart',    'rorchartr@scientificamerican.com', '1 High Crossing Point',    'Business Administration'),
  (29, 'Dayle',    'Ettery',     'detterys@springer.com',            '6693 Corben Road',         'Engineering'),
  (30, 'Auberon',  'Loadman',    'aloadmant@eepurl.com',             '08 Morrow Circle',         'Biology');
