USE university_explorer;

-- Country derived from city
SET NAMES utf8mb4;

UPDATE university SET country = 'AT' WHERE location IN (
  'Baden bei Wien',
  'Dornbirn',
  'Eisenstadt',
  'Feldkirch',
  'Graz',
  'Innsbruck',
  'Klagenfurt',
  'Krems an der Donau',
  'Kufstein',
  'Leoben',
  'Linz',
  'Puch bei Hallein',
  'Salzburg',
  'Seekirchen am Wallersee',
  'Spittal an der Drau',
  'St. Pölten',
  'Vienna',
  'Wels',
  'Wiener Neustadt'
);

UPDATE university SET country = 'BE' WHERE location IN (
  'Anderlecht',
  'Antwerp',
  'Brugge',
  'Brussels',
  'Diepenbeek',
  'Geel',
  'Gent',
  'Hasselt',
  'Ixelles',
  'Kortrijk',
  'Leuven',
  'Liège',
  'Louvain-La-Neuve',
  'Mechelen',
  'Mons',
  'Namur',
  'Schaarbeek',
  'Woluwe-Saint-Lambert'
);

UPDATE university SET country = 'BG' WHERE location IN (
  'Blagoevgrad',
  'Botevgrad',
  'Burgas',
  'Dolna Mitropolia',
  'Gabrovo',
  'Pernik',
  'Pleven',
  'Plovdiv',
  'Ruse',
  'Shumen',
  'Sofia',
  'Stara Zagora',
  'Svishtov',
  'Varna',
  'Veliko Tarnovo'
);

UPDATE university SET country = 'CY' WHERE location IN (
  'Famagusta',
  'Larnaca',
  'Larnaka',
  'Latsia',
  'Limassol',
  'Nicosia',
  'Paphos',
  'Strovolos'
);

UPDATE university SET country = 'CZ' WHERE location IN (
  'Brno',
  'Havířov',
  'Hradec Králové',
  'Liberec',
  'Mladá Bolesav',
  'Opava',
  'Ostrava',
  'Pardubice',
  'Plzeň',
  'Prague',
  'Zlín',
  'Ústí nad Labem',
  'České Budějovice'
);

UPDATE university SET country = 'DE' WHERE location IN (
  'Aachen',
  'Aalen',
  'Albstadt',
  'Altenholz',
  'Amberg',
  'Ansbach',
  'Aschaffenburg',
  'Augsburg',
  'Bad Homburg',
  'Bad Honnef',
  'Bamberg',
  'Bayreuth',
  'Berlin',
  'Biberach an der Riss',
  'Bielefeld',
  'Bingen am Rhein',
  'Bochum',
  'Bonn',
  'Brandenburg',
  'Braunschweig',
  'Bremen',
  'Bremerhaven',
  'Brühl',
  'Bückeburg',
  'Chemnitz',
  'Clausthal',
  'Coburg',
  'Cologne',
  'Cottbus',
  'Darmstadt',
  'Deggendorf',
  'Detmold',
  'Dortmund',
  'Dresden',
  'Düsseldorf',
  'Eberswalde',
  'Edenkoben',
  'Eichstätt',
  'Elmshorn',
  'Emden',
  'Erding',
  'Erfurt',
  'Erlangen',
  'Essen',
  'Esslingen am Neckar',
  'Flensburg',
  'Frankfurt (Oder)',
  'Frankfurt am Main',
  'Freiberg',
  'Freiburg im Breisgau',
  'Freising',
  'Friedrichshafen',
  'Fulda',
  'Furtwangen im Schwarzwald',
  'Fürstenfeldbruck',
  'Geisenheim',
  'Geislingen an der Steige',
  'Gelsenkirchen',
  'Gera',
  'Gießen',
  'Gotha',
  'Greifswald',
  'Göttingen',
  'Hachenburg',
  'Hagen',
  'Halle (Saale)',
  'Hamburg',
  'Hamm',
  'Hannover',
  'Heidelberg',
  'Heilbronn',
  'Hildesheim',
  'Hof',
  'Idstein',
  'Ilmenau',
  'Ingolstadt',
  'Iserlohn',
  'Jena',
  'Kaiserslautern',
  'Karlsruhe',
  'Kassel',
  'Kehl',
  'Kempten',
  'Kiel',
  'Kleve',
  'Koblenz',
  'Konstanz',
  'Königs Wusterhausen',
  'Köthen',
  'Landshut',
  'Leipzig',
  'Lemgo',
  'Ludwigsburg',
  'Ludwigshafen am Rhein',
  'Lübeck',
  'Lüneburg',
  'Magdeburg',
  'Mainz',
  'Mannheim',
  'Marburg',
  'Mayen',
  'Meißen',
  'Merseburg',
  'Mittweida',
  'Munich',
  'Möckern',
  'Mönchengladbach',
  'Mülheim an der Ruhr',
  'Münster',
  'Neu-Ulm',
  'Neubiberg',
  'Neubrandenburg',
  'Neuendettelsau',
  'Nordhausen',
  'Nordkirchen',
  'Nuremberg',
  'Oestrich-Winkel',
  'Offenbach am Main',
  'Offenburg',
  'Oldenburg',
  'Oranienburg',
  'Osnabrück',
  'Ottersberg',
  'Paderborn',
  'Passau',
  'Pfungstadt',
  'Potsdam',
  'Quierschied',
  'Regensburg',
  'Reutlingen',
  'Riedlingen',
  'Rosenheim',
  'Rostock',
  'Rotenburg an der Fulda',
  'Rottenburg am Neckar',
  'Saarbrücken',
  'Sankt Augustin',
  'Schmalkalden',
  'Schweinfurt',
  'Schwetzingen',
  'Schwäbisch Gmünd',
  'Siegen',
  'Speyer',
  'Stralsund',
  'Stuttgart',
  'Trier',
  'Trossingen',
  'Tübingen',
  'Ulm',
  'Vallendar',
  'Vechta',
  'Villingen-Schwenningen',
  'Weimar',
  'Weingarten',
  'Wernigerode',
  'Wiesbaden',
  'Wildau',
  'Wilhelmshaven',
  'Witten-Herdecke',
  'Wolfenbüttel',
  'Worms',
  'Wuppertal',
  'Würzburg',
  'Zittau',
  'Zwickau'
);

UPDATE university SET country = 'DK' WHERE location IN (
  'Aalborg',
  'Aarhus',
  'Birkerød',
  'Brøndby',
  'Copenhagen',
  'Esbjerg',
  'Fredericia',
  'Frederiksberg',
  'Frederikshavn',
  'Herning',
  'Hjørring',
  'Kolding',
  'Køge',
  'Lyngby',
  'Nuussuaq',
  'Odense',
  'Randers',
  'Risskov',
  'Roskilde',
  'Sorø',
  'Svendborg',
  'Tórshavn',
  'Vester Skerninge',
  'Viby'
);

UPDATE university SET country = 'EE' WHERE location IN (
  'Reola',
  'Tallinn',
  'Tartu'
);

UPDATE university SET country = 'ES' WHERE location IN (
  'A Coruña',
  'Alcalá de Henares',
  'Alfara del Patriarca',
  'Alicante',
  'Almería',
  'Arrasate',
  'Badajoz',
  'Barcelona',
  'Bilbao',
  'Burgos',
  'Cartagena',
  'Castelló de la Plana',
  'Ciudad Real',
  'Cádiz',
  'Córdoba',
  'Getafe',
  'Girona',
  'Granada',
  'Guadalupe',
  'Huelva',
  'Jaén',
  'Las Palmas de Gran Canaria',
  'Lejoa',
  'León',
  'Lleida',
  'Logroño',
  'Madrid',
  'Murcia',
  'Málaga',
  'Orotava (La)',
  'Oviedo',
  'Palma',
  'Pamplona',
  'Salamanca',
  'San Cristóbal de La Laguna',
  'Santa María de Guía de Gran Canaria',
  'Santander',
  'Santiago',
  'Santiago de Compostela',
  'Segovia',
  'Seville',
  'Tarragona',
  'Valladolid',
  'València',
  'Vic',
  'Vigo',
  'Villanueva de la Cañada',
  'Vitoria-Gasteiz',
  'Zaragoza',
  'Ávila'
);

UPDATE university SET country = 'FI' WHERE location IN (
  'Espoo',
  'Helsinki',
  'Hämeenlinna',
  'Joensuu',
  'Jyväskylä',
  'Kajaani',
  'Kokkola',
  'Kuopio',
  'Lahti',
  'Lappeenranta',
  'Maarianhamina - Mariehamn',
  'Mikkeli',
  'Oulu',
  'Pori',
  'Rovaniemi',
  'Seinäjoki',
  'Tampere',
  'Turku',
  'Vaasa',
  'Vantaa'
);

UPDATE university SET country = 'FR' WHERE location IN (
  'Besançon',
  'Bordeaux',
  'Brest',
  'Bruz',
  'Caen',
  'Dijon',
  'Grenoble',
  'La Rochelle',
  'Marseille',
  'Nîmes',
  'Pessac',
  'Rennes',
  'Saint-Étienne',
  'Toulouse',
  'Tours',
  'Troyes'
);

